# fly.toml app configuration file generated for airflow-bold-smoke-4258 on 2025-10-16T01:31:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ithacainsights-airflow"
primary_region = "ewr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  processes = ["webserver"]  

[[vm]]
  memory = "1gb"
  cpus = 1

[mounts]
  source = "airflow_data"
  destination = "/opt/airflow"

[[processes]]
  name = "webserver"
  command = "bash -c '/entrypoint.sh'"

[[processes]]
  name = "scheduler"
  command = "airflow scheduler"
